import type { Metadata } from "next";
import { Lora,   Inter } from "next/font/google";
import "./globals.css";
import Footer from '@/components/footer/Footer';	
import Navigation from '@/components/header/Navigation';
import UploadingOverlay from '@/components/actionProccessing/UploadingOverlay';
import DeletingOverlay from '@/components/actionProccessing/DeletingOverlay';
import 	MessageBox from '@/components/alertBox/MessageBox';

import { ContextStateProvider } from '@/context/contextState';


// Import Google Fonts
const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});
 

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white text-black">
      <body
        className={`   ${inter.variable} ${lora.variable}   antialiased`}
      >
				<ContextStateProvider>
					<MessageBox  />
          <UploadingOverlay />  
          <DeletingOverlay />  
					<Navigation />
					{children}
					<Footer />
				</ContextStateProvider>
			
			  
      </body>
    </html>
  );
}
